config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :statuses
  root to: 'statuses#index'

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :first_name, presence: true
  
  validates :last_name, presence: true
  
  validates :profile_name, presence: true,
  							uniqueness: true,
  							format: {
  							  with: /a-zA-Z0-9_-/,
  							  message: 'Must be formatted correctly.'
  							}
  has_many :statuses
         
  def full_name
      first_name + " " + last_name 
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:user_name, :last_name, :first_name] #add or remove parameters as needed
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def sign_up_params
     params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="contain-to-grid fixed">

<nav class="top-bar" data-topbar>
<ul class="title-area">
<li class="name"><h1><a href="#" id="name">Treebook</a></h1></li>
<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
</ul>

<section class="top-bar-section"> <!-- Right Nav Section -->
<ul class="left">
<li class="active"><%= link_to "All Statuses", statuses_path %></li>
</ul>

<ul class="right">

	<% if user_signed_in? %>	
	<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
	<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	
	<% else %>
		<li><%= link_to "Register", new_user_registration_path %></li>
		<li><%= link_to "Sign in", new_user_session_path %></li>
	<% end %>
	
</ul>
</section>
</nav>

</div>


<div class="row headerS">
	
	  <p class="notice"><%= notice %></p>
	
	<div data-alert class="alert-box info radius">
	  <p class="alert"><%= alert %></p>
	  <a href="#" class="close">&times;</a>
	</div>
	
	<%= yield %>
</div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="row">
	<div class="large-12 columns thS">
		<h1 class="statT left">Most Recent Statuses</h1>
		<%= link_to "Post a New Status", new_status_path, class: 'button success buttonSpacing' %>
		<!-- /.statT -->
		<hr class="line1" />
	</div>
	<!-- /.large-12 columns -->
</div>
<!-- /.row -->




<% @statuses.each do |status| %>

<div class="status">
	<h4><%= status.user.full_name %></h4>
	<p><%= status.content %></p>
	
	<div class="meta">
	<%= link_to time_ago_in_words(status.created_at) + " ago", status %>  
	
	<span class="admin">
		| <%= link_to "Edit", edit_status_path(status) %> | 
		<%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to do this bro?!" } %>
	</span>
	
	</div>
</div>
<!-- /.status -->

<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>